[package]
name = "o63"
description = "Toolkit for type-safe parsing and editing of vCards."
version = "0.1.1"
edition = "2024"
license = "AGPL-3.0-only"
homepage = "https://option63.eu"
repository = "https://github.com/conradkleinespel/option63"
keywords = ["vcard", "carddav", "o63", "option63"]

[dependencies]
thiserror = "2.0"
nom = "8"
actix-web = "4"
reqwest = { version = "0.13", default-features = false, features = ["http2", "rustls"] }
quick-xml = "0.42"
base64 = "0.23"
uuid = { version = "1", features = ["v4"] }
tracing = "0.1"
