[licenses]
allow = [
    "Apache-2.0",
    "MIT",
    "Unicode-3.0",
    "Zlib",
    "BSD-3-Clause"
]

[licenses.private]
ignore = true

[[licenses.exceptions]]
allow = ["AGPL-3.0-only"]
name = "o63"

[[licenses.exceptions]]
allow = ["AGPL-3.0-only"]
name = "o63_cli"

[[licenses.exceptions]]
allow = ["AGPL-3.0-only"]
name = "o63_derive"

[[licenses.exceptions]]
allow = ["AGPL-3.0-only"]
name = "o63_web"

[bans]
multiple-versions = "warn"

[sources]
unknown-registry = "warn"
unknown-git = "warn"

