[package]
name = "o63_web"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-only"

[[bin]]
name = "o63web"
path = "src/main.rs"

[dependencies]
actix-web = "4"
actix-files = "0.7"
askama = "0.16"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
o63 = { path = "../lib" }

[build-dependencies]
askama = "0.16"
